version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080
        depends_on:
            - database
            - redis
    
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
             MYSQL_DATABASE: default
             MYSQL_USER: laravel
             MYSQL_PASSWORD: secret
             MYSQL_ROOT_PASSWORD: secret
        volumes:
            - db-data:/var/lib/mysql
   
    redis:
        container_name:  redis
        image: redis/redis-stack:latest
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - 6380:6379

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"  # Map container port 80 to host port 8080
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: secret

    nginx:
        image: nginx:latest
        ports:
        - "80:80"
        volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro   # Mount nginx.conf to container
        - .:/var/www/html
        depends_on:
        - api
volumes:
    db-data: ~
